# Generated by Django 5.2.3 on 2025-07-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='identifier',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
