# Generated by Django 5.2.3 on 2025-07-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_manager_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='badge',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='member',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
